model: /apollo_workspace/ZL2/weights/yolov5s-cls-0401.pt
data: /apollo_workspace/ZL2/dataset/ClsDataSet
epochs: 5
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: ZL2/runs/train-cls
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: ZL2/runs/train-cls/exp
